### ISSUE TITLE
Add "Crust of Rust" series to intermediate learning resources

### ISSUE THREAD

**Issue by banocean** [ImplFerris/LearnRust#4]
Crust of Rust is @jonhoo's series on intermediate rust concepts, I think it fits perfectly into this list especially when we consider that other series by @jonhoo are on this list.

Youtube playlist: https://m.youtube.com/playlist?list=PLqbS7AVVErFiWDOAVrPt7aYmnuuOLYvOa

Since there is no clear contribution guidelines I just settled on creating an issue.

**Comment by ImplFerris** [comment]
Thank you, updated
